### ISSUE TITLE
Publish newest version of nodeos-nodejs on npm

### ISSUE THREAD

**Issue by luii** [NodeOS/nodejs#60]
Can we publish it with the new version (9.3.0) or do we have incompatabilites with any other dependency?

**Comment by piranna** [comment]
`nodeos-nodejs` releases are automatically on npm each time a new version is published upstream. Thing is for some reason it's not being published on npm, probably due to a problem with tokens. I'll need to review it.

**Comment by luii** [comment]
Ok good to hear it.

**Comment by piranna** [comment]
Publish of updated versions is working since several weeks ago, latests is 9.8.0. Clossing.
